### PR TITLE
4.1

### PR DESCRIPTION
**Pull request by cirosantilli**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@dgoulet: It is possible to add last 4.1.1 version?

And can you add ownership to OTR team?
- http://otr.im/people.html
-> @claucece @DrWhax @olabini
It will be nice to have only one place for all.

**Comment by DrWhax** [comment]
This is merely an outdated mirror it seems.

I have control over this as well.

@Neustradamus I know you mean well, but this is a mirror and nobody really needs access to it, it just needs a push on a new release. That's it.

**Comment by Neustradamus** [comment]
@DrWhax: When we look (only) here: Watch:12 / Star:48 / Fork:14
Maybe good to be better, no? ;)
Really bad to separate all people in this not-up-to-date repository and other too, and OTRv4.
There is no strategy... strange no?
No "service quality"... you must to change bad points.
Two websites, ... already said.
If it is hard for you to update libs/softs for be up-to-date, you can remove all, lost all, and publish (mirror) a new time for have all history of OTR.
Thanks in advance.

**Comment by DrWhax** [comment]
You're replying to an old pull request from 4 years ago! Why??

If you feel very strongly about it, open a new ticket. Locking this discussion.

**Pull request merged**
